language: node_js
node_js:
- 6
branches:
  only:
  - dev
  except:
  - gh-pages
env:
  global:
  - SSH_KEY="assets/id_rsa"
  - GIT_NAME="Haroen Viaene [bot]"
  - GIT_EMAIL="hello@haroen.me"
  - SOURCE_DIR="."
  - DEPLOY_BRANCH="dev"
script:
- yarn run update
- curl -s -o src/data/speelterreinen.geojson https://datatank.stad.gent/4/cultuursportvrijetijd/speelterreinen.geojson
- curl -s -o src/data/clubhuizenvoorsenioren.geojson https://datatank.stad.gent/4/doelgroepen/clubhuizenvoorsenioren.geojson
- curl -s -o src/data/hondenvoorzieningen.geojson https://datatank.stad.gent/4/infrastructuur/hondenvoorzieningen.geojson
after_success:
- yarn run gh-pages-travis
before_install:
- openssl aes-256-cbc -K $encrypted_b7f2d4134afc_key -iv $encrypted_b7f2d4134afc_iv
  -in id_rsa.enc -out assets/id_rsa -d
