# the language
lang: nl
# author info
author: [Haroen Viaene, Elias Meire, Simon Wydooghe]
# title and description
title: Ik Haat Gent
description: Vermijd wat je haat in Gent
# the url this will be published at
url: 'http://ikhaat.gent'
# the theme colour
color: '#354EA0'
# location of some files
css: 'src/style.css'
scripts:
  - 'https://cdn.firebase.com/js/client/2.4.1/firebase.js'
  - 'http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js'
  - 'https://code.jquery.com/jquery-2.2.2.min.js'
  - 'src/main.js'
favicon: 'src/apple-touch-icon.png'
#configuration
sass:
  style: compressed
