/*
This has been generated by the overpass-turbo wizard.
The original search was:
“tourism in ghent”
http://overpass-turbo.eu/s/f8j
*/
[out:json][timeout:25];
// fetch area “ghent” to search in
area(3600897671)->.searchArea;
// gather results
(
  // query part for: “tourism”
  node["tourism"](area.searchArea);
  way["tourism"](area.searchArea);
  relation["tourism"](area.searchArea);
);
// print results
out body;
>;
out skel qt;
